### ISSUE TITLE
What is the license for the logo?

### ISSUE THREAD

**Issue by sdruskat** [citation-style-language/logo#2]
It'd be good to clarify this in the repository by including a license file perhaps.

**Comment by flachware** [comment]
@rmzelle @inukshuk I think the logo – as a visual ID – should not be remixed, so maybe a license like CC BY-ND could be appropriate?

**Comment by inukshuk** [comment]
Sounds good to me!

**Comment by rmzelle** [comment]
@sdruskat, @flachware, thanks! Closed per https://github.com/citation-style-language/logo/pull/3.
